create table consultas(

    id bigint generated by default as identity,
    medico_id bigint not null,
    paciente varchar(100) not null,
    data timestamp not null,

    primary key(id),
    constraint fk_consultas_medico_id foreign key(medico_id) references medicos(id)

);